### ISSUE TITLE
Mass issues not currently working due to lack of tzdata in linux container

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/konmaripo#117]
When we switched containers as part of #103, I neglected to note that the container didn't come with tz data.

Mass issues is currently failing to load with the below error from the logs:

```
2020-08-25T16:06:33.554542144Z [16:06:33 ERR] HTTP GET /MassIssues responded 500 in 38.3882 ms
2020-08-25T16:06:33.554584145Z System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.
2020-08-25T16:06:33.554591045Z    at TimeZoneConverter.TZConvert.GetTimeZoneInfo(String windowsOrIanaTimeZoneId)
2020-08-25T16:06:33.555620350Z    at Konmaripo.Web.Services.GitHubService.APITokenResetTime() in /src/Konmaripo.Web/Services/GitHubService.cs:line 128
2020-08-25T16:06:33.555634351Z    at Konmaripo.Web.Services.CachedGitHubService.APITokenResetTime() in /src/Konmaripo.Web/Services/CachedGitHubService.cs:line 90
2020-08-25T16:06:33.555639451Z    at Konmaripo.Web.Controllers.MassIssuesController.Index() in /src/Konmaripo.Web/Controllers/MassIssuesController.cs:line 73
```

This led me to this helpful information: https://github.com/mj1856/TimeZoneConverter#note-on-os-data-dependencies

**Comment by SeanKilleen** [comment]
Note to self: acceptance tests that run against a container could have prevented this.
